### ISSUE TITLE
MFE footer links too close together

### ISSUE THREAD

**Issue by igobranco** [fccn/frontend-component-footer-nau#15]
The footer links on the MFEs are too close together, preventing someone to easily click on the correct link using a mobile phone.

We need to increase the spacing between each footer link.

![Image](https://github.com/user-attachments/assets/d230b958-2fdd-4999-8c27-77ca8e9d7cd5)

**Comment by sandroscosta** [comment]
I'll put this in a future "sprint" all dedicated to the accessibility of the LMS. It's something that we have to think about.

**Comment by igobranco** [comment]
Fixed. Used the spacing of Richie.
